- name: Create Development folder
  ansible.builtin.file:
    path: ~/Development
    state: directory
  tags:
    - base

- name: Create Personal folder
  ansible.builtin.file:
    path: ~/Development/Personal
    state: directory
  tags:
    - base

- name: Clone dotfiles
  ansible.builtin.git:
    repo: https://github.com/guifrrs/dotfiles
    dest: ~/Development/Personal/dotfiles
    update: true
  tags:
    - base

- name: Install base packages
  community.general.homebrew:
    name: "{{ base }}"
  tags:
    - base

- name: Include zsh task
  ansible.builtin.include_tasks:
    file: zsh.yml

- name: Install JetBrains Mono font
  ansible.builtin.homebrew_cask:
    name: jetbrains-mono
  tags:
    - base
