- name: Check if oh-my-zsh already exists
  ansible.builtin.stat:
    path: ~/.oh-my-zsh
  register: oh_my_zsh_check

- name: Install Oh My ZSH
  when: oh_my_zsh_check.stat.exists == false
  ansible.builtin.shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  register: oh_my_zsh_install
  changed_when: oh_my_zsh_install.rc == 0

- name: Check if .zshrc exists on user home folder
  ansible.builtin.stat:
    path: ~/.zshrc
  register: zsh_file_check
  tags:
    - zsh

- name: Create symlink between dotfiles and .zshrc
  when: zsh_file_check.stat.exists == true
  ansible.builtin.file:
    src: ~/Development/Personal/dotfiles/.zshrc
    dest: ~/.zshrc
    state: link
    force: true
  tags:
    - zsh

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    version: master
  tags:
    - zsh

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    version: master
  tags:
    - zsh

- name: Install zsh-completions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-completions.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-completions
    version: master
  tags:
    - zsh